### PR TITLE
Add .editorconfig file to the repo.

### PR DESCRIPTION
**Pull request by StevenBlack**
This helps contributors conform to existing coding style.

### CODE REVIEW

**Comment by davestewart** [comment]
Mate, you're a legend - I find all this config stuff *hugely* tedious!

**Comment by StevenBlack** [comment]
As long as your favourite editor supports it;  not all do.

**Comment by demisx** [comment]
And why this hasn’t been merged for almost 2 years now? 😀

**Comment by davestewart** [comment]
Probably because I keep planning to make updates but don't get round to it!

**Comment by davestewart** [comment]
Nothing a slightly sarky comment can't help solve though 😉

**Comment by demisx** [comment]
I am sorry, I didn't mean to sound this way. I am evaluating different JSMs for our team, including this one. A big emphasis is put on whether the core team responds to open issues and PRs promptly, thus the project is still being actively maintained. I just couldn't help myself wondering why such a simple PR would be dangling for so long. My apologies. I should've written my question differently. Your hard work is truly appreciated.

**Comment by davestewart** [comment]
Ha! Don't worry, not sure where you're from, I'm a Brit and sarcasm comes as standard.

As for updates, this has not had an update in a long time. Honestly, I wrote the lib thinking I would be using it a lot... and I never really did. A shame, as there's some great code in there.

For v2, I would like to split the DSL stuff out to a plugin, so the SM itself would be a bit more lightweight. It would most likely decorate the methods to accept strings as well as objects, and of course would extract the core parser code from the SM management itself.

It is also sorely crying out for tests, which I generally didn't used to write, but I've started in the last few months, so that's a challenge waiting to be accepted.

As for updates, and the lib being supported... I wish I could say it was, but it hasn't been!

See how you go. If you need my help, fire a sarcy shot across my bows; I dare you 😜

**Comment by demisx** [comment]
Appreciate cool attitude and being honest about the project, mate!

**Pull request merged**
