### PR TITLE
Push state names into vue-router to navigate to named routes.

### LINKED ISSUE #14: Using vue-router with StateHelper pushes state names as route paths instead of as route names
Steps to reproduce:

Modify the route paths in the example `demo/html/examples/vue/vue-router.html` vue-router configuration lines 59-69:
```
var router = new VueRouter({
    mode: 'hash',

    // note that route names match state names
    routes: [
        { path: '/state-a', name: 'a', component: StateA },
        { path: '/state-b', name: 'b', component: StateB },
        { path: '/state-c', name: 'c', component: StateC },
        { path: '*',  name: '*', component: NotFound }
    ]
});
```

Run:
```
npm run demo
```

### PR DESCRIPTION
**Pull request by twoBoots**
Updated VueRouter helper to navigate to named routes. Fixes #14

### CODE REVIEW

**Comment by davestewart** [comment]
Nice work! I didn't realise you could push an object with a named route.

**Comment by leevigraham** [comment]
Has a new version been pushed with this fix?

**Comment by davestewart** [comment]
I'll do that now :)

**Comment by davestewart** [comment]
@leevigraham - done :)

**Comment by leevigraham** [comment]
@davestewart played with the lib last night, managed to build a pretty complex vuejs form without much trouble. Nice work.

**Comment by davestewart** [comment]
@leevigraham thanks mate!

Keep meaning to get round to building the next version, but you know... day job :P

**Pull request merged**
